name: 'Open release branch'
on:
  issues:
    types: [opened]

jobs:
  create-release-branch:
    name: "create release branch"
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}